// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdtpzixriyzwykhffaxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkdHB6aXhyaXl6d3lraGZmYXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDM0MTAsImV4cCI6MjA2MTYxOTQxMH0.zLVeUBvrD6geW9Xwb87cVzaBniHiFNcpwRh_WZO6H3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});